apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: apurvpod
  name: apurvpod
spec:
  containers:
  - command: ["/bin/sh", "-c", "ping fb.com"]
    image: alpine
    name: apurvcontainer-0
  - command: ["/bin/sh", "-c", "sleep 1000000"]
    image: busybox
    name: apurvcontainer-1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}

